# Generated by Django 6.0.5 on 2026-07-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_cep_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_cep',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_complement',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_label',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_neighborhood',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
