# Generated by Django 6.0.1 on 2026-01-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
