# Generated by Django 6.0.1 on 2026-02-09 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_is_available_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='minimum_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'The minimum stock quantity must be zero or a positive number.')]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'The stock quantity must be zero or a positive number.')]),
        ),
    ]
