# Generated by Django 6.0.1 on 2026-02-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_stock_minimum_stock_alter_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
