# Generated by Django 6.0.1 on 2026-03-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_complement_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementgroup',
            name='complements',
        ),
        migrations.AddField(
            model_name='complement',
            name='complement_group',
            field=models.ManyToManyField(to='menu.complementgroup'),
        ),
    ]
