# Generated by Django 6.0.1 on 2026-04-06 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_rename_complement_complementgroup_complements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementgroup',
            name='max_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='complementgroup',
            name='min_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
