# Generated by Django 6.0.1 on 2026-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_complementgroup_complements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complement',
            name='complement_group',
        ),
        migrations.AddField(
            model_name='complementgroup',
            name='complement',
            field=models.ManyToManyField(to='menu.complement'),
        ),
    ]
