# Generated by Django 6.0.1 on 2026-03-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_remove_complement_complement_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complementgroup',
            old_name='complement',
            new_name='complements',
        ),
    ]
